package yxinfo.dct.service.base.dao.model;

import java.util.Date;

public class SysAccessTok {
    //AccessToken
    private String accessTok;

    //设备类型（1PC, 2APP）
    private String deviceType;

    //创建时间
    private Date createAt;

    //成员id
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.access_tok
     *
     * @return the value of sys_access_tok.access_tok
     *
     * @mbggenerated
     */
    public String getAccessTok() {
        return accessTok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.access_tok
     *
     * @param accessTok the value for sys_access_tok.access_tok
     *
     * @mbggenerated
     */
    public void setAccessTok(String accessTok) {
        this.accessTok = accessTok == null ? null : accessTok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.device_type
     *
     * @return the value of sys_access_tok.device_type
     *
     * @mbggenerated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.device_type
     *
     * @param deviceType the value for sys_access_tok.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.create_at
     *
     * @return the value of sys_access_tok.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.create_at
     *
     * @param createAt the value for sys_access_tok.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_access_tok.member_id
     *
     * @return the value of sys_access_tok.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_access_tok.member_id
     *
     * @param memberId the value for sys_access_tok.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}