package yxinfo.dct.service.base.dao.model;

import java.util.Date;

public class SysGroup {
    private Integer id;

    //名称
    private String fname;

    //成员组编号
    private String fcode;

    //名称拼音
    private String pyinName;

    private String remark;

    //所属组织
    private Integer orgId;

    //父成员组id
    private Integer pid;

    //创建时间
    private Date createAt;

    //更新时间
    private Date updateAt;

    //是否被删除（1是, 0否）
    private Boolean isDel;

    //排序
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.id
     *
     * @return the value of sys_group.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.id
     *
     * @param id the value for sys_group.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.fname
     *
     * @return the value of sys_group.fname
     *
     * @mbggenerated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.fname
     *
     * @param fname the value for sys_group.fname
     *
     * @mbggenerated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.fcode
     *
     * @return the value of sys_group.fcode
     *
     * @mbggenerated
     */
    public String getFcode() {
        return fcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.fcode
     *
     * @param fcode the value for sys_group.fcode
     *
     * @mbggenerated
     */
    public void setFcode(String fcode) {
        this.fcode = fcode == null ? null : fcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.pyin_name
     *
     * @return the value of sys_group.pyin_name
     *
     * @mbggenerated
     */
    public String getPyinName() {
        return pyinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.pyin_name
     *
     * @param pyinName the value for sys_group.pyin_name
     *
     * @mbggenerated
     */
    public void setPyinName(String pyinName) {
        this.pyinName = pyinName == null ? null : pyinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.remark
     *
     * @return the value of sys_group.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.remark
     *
     * @param remark the value for sys_group.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.org_id
     *
     * @return the value of sys_group.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.org_id
     *
     * @param orgId the value for sys_group.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.pid
     *
     * @return the value of sys_group.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.pid
     *
     * @param pid the value for sys_group.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.create_at
     *
     * @return the value of sys_group.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.create_at
     *
     * @param createAt the value for sys_group.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.update_at
     *
     * @return the value of sys_group.update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.update_at
     *
     * @param updateAt the value for sys_group.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.is_del
     *
     * @return the value of sys_group.is_del
     *
     * @mbggenerated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.is_del
     *
     * @param isDel the value for sys_group.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.sort
     *
     * @return the value of sys_group.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.sort
     *
     * @param sort the value for sys_group.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}