package yxinfo.dct.service.base.dao.model;

public class SysMbrInput {
    private Integer id;

    //登录名
    private String loginName;

    //人员编号
    private String fcode;

    //真实姓名
    private String realName;

    //组织id
    private Integer orgId;

    private String groups;

    private String roles;

    private String tags;

    //姓名拼音
    private String pyinName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_mbr_input.id
     *
     * @return the value of sys_mbr_input.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_mbr_input.id
     *
     * @param id the value for sys_mbr_input.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_mbr_input.login_name
     *
     * @return the value of sys_mbr_input.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_mbr_input.login_name
     *
     * @param loginName the value for sys_mbr_input.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_mbr_input.fcode
     *
     * @return the value of sys_mbr_input.fcode
     *
     * @mbggenerated
     */
    public String getFcode() {
        return fcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_mbr_input.fcode
     *
     * @param fcode the value for sys_mbr_input.fcode
     *
     * @mbggenerated
     */
    public void setFcode(String fcode) {
        this.fcode = fcode == null ? null : fcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_mbr_input.real_name
     *
     * @return the value of sys_mbr_input.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_mbr_input.real_name
     *
     * @param realName the value for sys_mbr_input.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_mbr_input.org_id
     *
     * @return the value of sys_mbr_input.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_mbr_input.org_id
     *
     * @param orgId the value for sys_mbr_input.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_mbr_input.groups
     *
     * @return the value of sys_mbr_input.groups
     *
     * @mbggenerated
     */
    public String getGroups() {
        return groups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_mbr_input.groups
     *
     * @param groups the value for sys_mbr_input.groups
     *
     * @mbggenerated
     */
    public void setGroups(String groups) {
        this.groups = groups == null ? null : groups.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_mbr_input.roles
     *
     * @return the value of sys_mbr_input.roles
     *
     * @mbggenerated
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_mbr_input.roles
     *
     * @param roles the value for sys_mbr_input.roles
     *
     * @mbggenerated
     */
    public void setRoles(String roles) {
        this.roles = roles == null ? null : roles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_mbr_input.tags
     *
     * @return the value of sys_mbr_input.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_mbr_input.tags
     *
     * @param tags the value for sys_mbr_input.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_mbr_input.pyin_name
     *
     * @return the value of sys_mbr_input.pyin_name
     *
     * @mbggenerated
     */
    public String getPyinName() {
        return pyinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_mbr_input.pyin_name
     *
     * @param pyinName the value for sys_mbr_input.pyin_name
     *
     * @mbggenerated
     */
    public void setPyinName(String pyinName) {
        this.pyinName = pyinName == null ? null : pyinName.trim();
    }
}