package yxinfo.dct.service.base.dao.model;

public class SysMemberOrgRole {
    private Integer id;

    //成员id
    private Integer memberId;

    //所属组织id
    private Integer orgId;

    //所属角色id
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org_role.id
     *
     * @return the value of sys_member_org_role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org_role.id
     *
     * @param id the value for sys_member_org_role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org_role.member_id
     *
     * @return the value of sys_member_org_role.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org_role.member_id
     *
     * @param memberId the value for sys_member_org_role.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org_role.org_id
     *
     * @return the value of sys_member_org_role.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org_role.org_id
     *
     * @param orgId the value for sys_member_org_role.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_org_role.role_id
     *
     * @return the value of sys_member_org_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_org_role.role_id
     *
     * @param roleId the value for sys_member_org_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}