package yxinfo.dct.service.base.dao.model;

public class SysMemberTag {
    private Integer id;

    //成员id
    private Integer memberId;

    //标签id
    private Integer tagId;

    //组织id
    private Integer orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_tag.id
     *
     * @return the value of sys_member_tag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_tag.id
     *
     * @param id the value for sys_member_tag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_tag.member_id
     *
     * @return the value of sys_member_tag.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_tag.member_id
     *
     * @param memberId the value for sys_member_tag.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_tag.tag_id
     *
     * @return the value of sys_member_tag.tag_id
     *
     * @mbggenerated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_tag.tag_id
     *
     * @param tagId the value for sys_member_tag.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member_tag.org_id
     *
     * @return the value of sys_member_tag.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member_tag.org_id
     *
     * @param orgId the value for sys_member_tag.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
}