package yxinfo.dct.service.base.dao.model;

public class SysOrgTerminal {
    private String termCode;

    private Integer orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_terminal.term_code
     *
     * @return the value of sys_org_terminal.term_code
     *
     * @mbggenerated
     */
    public String getTermCode() {
        return termCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_terminal.term_code
     *
     * @param termCode the value for sys_org_terminal.term_code
     *
     * @mbggenerated
     */
    public void setTermCode(String termCode) {
        this.termCode = termCode == null ? null : termCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_terminal.org_id
     *
     * @return the value of sys_org_terminal.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_terminal.org_id
     *
     * @param orgId the value for sys_org_terminal.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
}