package yxinfo.dct.service.base.dao.model;

import java.util.Date;

public class SysOrg {
    private Integer id;

    //组织编号
    private String fcode;

    //名称
    private String fname;

    //拼音名称
    private String pyinName;

    //地址
    private String address;

    //上级组织
    private Integer pid;

    //创建时间
    private Date createAt;

    //更新时间
    private Date updateAt;

    //是否被删除（1是, 0否）
    private Boolean isDel;

    //排序
    private Integer sort;

    //组织余额（分）
    private Integer bal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.id
     *
     * @return the value of sys_org.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.id
     *
     * @param id the value for sys_org.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.fcode
     *
     * @return the value of sys_org.fcode
     *
     * @mbggenerated
     */
    public String getFcode() {
        return fcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.fcode
     *
     * @param fcode the value for sys_org.fcode
     *
     * @mbggenerated
     */
    public void setFcode(String fcode) {
        this.fcode = fcode == null ? null : fcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.fname
     *
     * @return the value of sys_org.fname
     *
     * @mbggenerated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.fname
     *
     * @param fname the value for sys_org.fname
     *
     * @mbggenerated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.pyin_name
     *
     * @return the value of sys_org.pyin_name
     *
     * @mbggenerated
     */
    public String getPyinName() {
        return pyinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.pyin_name
     *
     * @param pyinName the value for sys_org.pyin_name
     *
     * @mbggenerated
     */
    public void setPyinName(String pyinName) {
        this.pyinName = pyinName == null ? null : pyinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.address
     *
     * @return the value of sys_org.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.address
     *
     * @param address the value for sys_org.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.pid
     *
     * @return the value of sys_org.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.pid
     *
     * @param pid the value for sys_org.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.create_at
     *
     * @return the value of sys_org.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.create_at
     *
     * @param createAt the value for sys_org.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.update_at
     *
     * @return the value of sys_org.update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.update_at
     *
     * @param updateAt the value for sys_org.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.is_del
     *
     * @return the value of sys_org.is_del
     *
     * @mbggenerated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.is_del
     *
     * @param isDel the value for sys_org.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.sort
     *
     * @return the value of sys_org.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.sort
     *
     * @param sort the value for sys_org.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.bal
     *
     * @return the value of sys_org.bal
     *
     * @mbggenerated
     */
    public Integer getBal() {
        return bal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.bal
     *
     * @param bal the value for sys_org.bal
     *
     * @mbggenerated
     */
    public void setBal(Integer bal) {
        this.bal = bal;
    }
}