package yxinfo.dct.service.base.dao.model;

import java.util.ArrayList;
import java.util.List;
import yxinfo.dct.framework.service.dal.Page;
import yxinfo.dct.framework.service.dal.dao.AbstractModel;

public class SysOrgCustomizedExample extends AbstractModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public SysOrgCustomizedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("org_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("org_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(Integer value) {
            addCriterion("org_id =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(Integer value) {
            addCriterion("org_id <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(Integer value) {
            addCriterion("org_id >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("org_id >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(Integer value) {
            addCriterion("org_id <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(Integer value) {
            addCriterion("org_id <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<Integer> values) {
            addCriterion("org_id in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<Integer> values) {
            addCriterion("org_id not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(Integer value1, Integer value2) {
            addCriterion("org_id between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("org_id not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andLogo1IsNull() {
            addCriterion("logo1 is null");
            return (Criteria) this;
        }

        public Criteria andLogo1IsNotNull() {
            addCriterion("logo1 is not null");
            return (Criteria) this;
        }

        public Criteria andLogo1EqualTo(String value) {
            addCriterion("logo1 =", value, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1NotEqualTo(String value) {
            addCriterion("logo1 <>", value, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1GreaterThan(String value) {
            addCriterion("logo1 >", value, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1GreaterThanOrEqualTo(String value) {
            addCriterion("logo1 >=", value, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1LessThan(String value) {
            addCriterion("logo1 <", value, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1LessThanOrEqualTo(String value) {
            addCriterion("logo1 <=", value, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1Like(String value) {
            addCriterion("logo1 like", value, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1NotLike(String value) {
            addCriterion("logo1 not like", value, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1In(List<String> values) {
            addCriterion("logo1 in", values, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1NotIn(List<String> values) {
            addCriterion("logo1 not in", values, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1Between(String value1, String value2) {
            addCriterion("logo1 between", value1, value2, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo1NotBetween(String value1, String value2) {
            addCriterion("logo1 not between", value1, value2, "logo1");
            return (Criteria) this;
        }

        public Criteria andLogo2IsNull() {
            addCriterion("logo2 is null");
            return (Criteria) this;
        }

        public Criteria andLogo2IsNotNull() {
            addCriterion("logo2 is not null");
            return (Criteria) this;
        }

        public Criteria andLogo2EqualTo(String value) {
            addCriterion("logo2 =", value, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2NotEqualTo(String value) {
            addCriterion("logo2 <>", value, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2GreaterThan(String value) {
            addCriterion("logo2 >", value, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2GreaterThanOrEqualTo(String value) {
            addCriterion("logo2 >=", value, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2LessThan(String value) {
            addCriterion("logo2 <", value, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2LessThanOrEqualTo(String value) {
            addCriterion("logo2 <=", value, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2Like(String value) {
            addCriterion("logo2 like", value, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2NotLike(String value) {
            addCriterion("logo2 not like", value, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2In(List<String> values) {
            addCriterion("logo2 in", values, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2NotIn(List<String> values) {
            addCriterion("logo2 not in", values, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2Between(String value1, String value2) {
            addCriterion("logo2 between", value1, value2, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo2NotBetween(String value1, String value2) {
            addCriterion("logo2 not between", value1, value2, "logo2");
            return (Criteria) this;
        }

        public Criteria andLogo3IsNull() {
            addCriterion("logo3 is null");
            return (Criteria) this;
        }

        public Criteria andLogo3IsNotNull() {
            addCriterion("logo3 is not null");
            return (Criteria) this;
        }

        public Criteria andLogo3EqualTo(String value) {
            addCriterion("logo3 =", value, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3NotEqualTo(String value) {
            addCriterion("logo3 <>", value, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3GreaterThan(String value) {
            addCriterion("logo3 >", value, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3GreaterThanOrEqualTo(String value) {
            addCriterion("logo3 >=", value, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3LessThan(String value) {
            addCriterion("logo3 <", value, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3LessThanOrEqualTo(String value) {
            addCriterion("logo3 <=", value, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3Like(String value) {
            addCriterion("logo3 like", value, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3NotLike(String value) {
            addCriterion("logo3 not like", value, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3In(List<String> values) {
            addCriterion("logo3 in", values, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3NotIn(List<String> values) {
            addCriterion("logo3 not in", values, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3Between(String value1, String value2) {
            addCriterion("logo3 between", value1, value2, "logo3");
            return (Criteria) this;
        }

        public Criteria andLogo3NotBetween(String value1, String value2) {
            addCriterion("logo3 not between", value1, value2, "logo3");
            return (Criteria) this;
        }

        public Criteria andBanner1IsNull() {
            addCriterion("banner1 is null");
            return (Criteria) this;
        }

        public Criteria andBanner1IsNotNull() {
            addCriterion("banner1 is not null");
            return (Criteria) this;
        }

        public Criteria andBanner1EqualTo(String value) {
            addCriterion("banner1 =", value, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1NotEqualTo(String value) {
            addCriterion("banner1 <>", value, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1GreaterThan(String value) {
            addCriterion("banner1 >", value, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1GreaterThanOrEqualTo(String value) {
            addCriterion("banner1 >=", value, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1LessThan(String value) {
            addCriterion("banner1 <", value, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1LessThanOrEqualTo(String value) {
            addCriterion("banner1 <=", value, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1Like(String value) {
            addCriterion("banner1 like", value, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1NotLike(String value) {
            addCriterion("banner1 not like", value, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1In(List<String> values) {
            addCriterion("banner1 in", values, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1NotIn(List<String> values) {
            addCriterion("banner1 not in", values, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1Between(String value1, String value2) {
            addCriterion("banner1 between", value1, value2, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner1NotBetween(String value1, String value2) {
            addCriterion("banner1 not between", value1, value2, "banner1");
            return (Criteria) this;
        }

        public Criteria andBanner2IsNull() {
            addCriterion("banner2 is null");
            return (Criteria) this;
        }

        public Criteria andBanner2IsNotNull() {
            addCriterion("banner2 is not null");
            return (Criteria) this;
        }

        public Criteria andBanner2EqualTo(String value) {
            addCriterion("banner2 =", value, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2NotEqualTo(String value) {
            addCriterion("banner2 <>", value, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2GreaterThan(String value) {
            addCriterion("banner2 >", value, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2GreaterThanOrEqualTo(String value) {
            addCriterion("banner2 >=", value, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2LessThan(String value) {
            addCriterion("banner2 <", value, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2LessThanOrEqualTo(String value) {
            addCriterion("banner2 <=", value, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2Like(String value) {
            addCriterion("banner2 like", value, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2NotLike(String value) {
            addCriterion("banner2 not like", value, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2In(List<String> values) {
            addCriterion("banner2 in", values, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2NotIn(List<String> values) {
            addCriterion("banner2 not in", values, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2Between(String value1, String value2) {
            addCriterion("banner2 between", value1, value2, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner2NotBetween(String value1, String value2) {
            addCriterion("banner2 not between", value1, value2, "banner2");
            return (Criteria) this;
        }

        public Criteria andBanner3IsNull() {
            addCriterion("banner3 is null");
            return (Criteria) this;
        }

        public Criteria andBanner3IsNotNull() {
            addCriterion("banner3 is not null");
            return (Criteria) this;
        }

        public Criteria andBanner3EqualTo(String value) {
            addCriterion("banner3 =", value, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3NotEqualTo(String value) {
            addCriterion("banner3 <>", value, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3GreaterThan(String value) {
            addCriterion("banner3 >", value, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3GreaterThanOrEqualTo(String value) {
            addCriterion("banner3 >=", value, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3LessThan(String value) {
            addCriterion("banner3 <", value, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3LessThanOrEqualTo(String value) {
            addCriterion("banner3 <=", value, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3Like(String value) {
            addCriterion("banner3 like", value, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3NotLike(String value) {
            addCriterion("banner3 not like", value, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3In(List<String> values) {
            addCriterion("banner3 in", values, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3NotIn(List<String> values) {
            addCriterion("banner3 not in", values, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3Between(String value1, String value2) {
            addCriterion("banner3 between", value1, value2, "banner3");
            return (Criteria) this;
        }

        public Criteria andBanner3NotBetween(String value1, String value2) {
            addCriterion("banner3 not between", value1, value2, "banner3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_org_customized
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_org_customized
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}