package yxinfo.dct.service.base.dao.model;

public class SysOrgCustomized {
    private Integer orgId;

    private String logo1;

    private String logo2;

    private String logo3;

    private String banner1;

    private String banner2;

    private String banner3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_customized.org_id
     *
     * @return the value of sys_org_customized.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_customized.org_id
     *
     * @param orgId the value for sys_org_customized.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_customized.logo1
     *
     * @return the value of sys_org_customized.logo1
     *
     * @mbggenerated
     */
    public String getLogo1() {
        return logo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_customized.logo1
     *
     * @param logo1 the value for sys_org_customized.logo1
     *
     * @mbggenerated
     */
    public void setLogo1(String logo1) {
        this.logo1 = logo1 == null ? null : logo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_customized.logo2
     *
     * @return the value of sys_org_customized.logo2
     *
     * @mbggenerated
     */
    public String getLogo2() {
        return logo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_customized.logo2
     *
     * @param logo2 the value for sys_org_customized.logo2
     *
     * @mbggenerated
     */
    public void setLogo2(String logo2) {
        this.logo2 = logo2 == null ? null : logo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_customized.logo3
     *
     * @return the value of sys_org_customized.logo3
     *
     * @mbggenerated
     */
    public String getLogo3() {
        return logo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_customized.logo3
     *
     * @param logo3 the value for sys_org_customized.logo3
     *
     * @mbggenerated
     */
    public void setLogo3(String logo3) {
        this.logo3 = logo3 == null ? null : logo3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_customized.banner1
     *
     * @return the value of sys_org_customized.banner1
     *
     * @mbggenerated
     */
    public String getBanner1() {
        return banner1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_customized.banner1
     *
     * @param banner1 the value for sys_org_customized.banner1
     *
     * @mbggenerated
     */
    public void setBanner1(String banner1) {
        this.banner1 = banner1 == null ? null : banner1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_customized.banner2
     *
     * @return the value of sys_org_customized.banner2
     *
     * @mbggenerated
     */
    public String getBanner2() {
        return banner2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_customized.banner2
     *
     * @param banner2 the value for sys_org_customized.banner2
     *
     * @mbggenerated
     */
    public void setBanner2(String banner2) {
        this.banner2 = banner2 == null ? null : banner2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org_customized.banner3
     *
     * @return the value of sys_org_customized.banner3
     *
     * @mbggenerated
     */
    public String getBanner3() {
        return banner3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org_customized.banner3
     *
     * @param banner3 the value for sys_org_customized.banner3
     *
     * @mbggenerated
     */
    public void setBanner3(String banner3) {
        this.banner3 = banner3 == null ? null : banner3.trim();
    }
}