package yxinfo.dct.service.base.dao.model;

public class SysRoleAppMenu {
    private Integer id;

    //成员组id
    private Integer roleId;

    //菜单id
    private Integer amId;

    //排序
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_app_menu.id
     *
     * @return the value of sys_role_app_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_app_menu.id
     *
     * @param id the value for sys_role_app_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_app_menu.role_id
     *
     * @return the value of sys_role_app_menu.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_app_menu.role_id
     *
     * @param roleId the value for sys_role_app_menu.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_app_menu.am_id
     *
     * @return the value of sys_role_app_menu.am_id
     *
     * @mbggenerated
     */
    public Integer getAmId() {
        return amId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_app_menu.am_id
     *
     * @param amId the value for sys_role_app_menu.am_id
     *
     * @mbggenerated
     */
    public void setAmId(Integer amId) {
        this.amId = amId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_app_menu.sort
     *
     * @return the value of sys_role_app_menu.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_app_menu.sort
     *
     * @param sort the value for sys_role_app_menu.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}