package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysAccessTok;
import yxinfo.dct.service.base.dao.model.SysAccessTokExample;

public interface SysAccessTokMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    int countByExample(SysAccessTokExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    int deleteByExample(SysAccessTokExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String accessTok);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    int insert(SysAccessTok record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    int insertSelective(SysAccessTok record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    List<SysAccessTok> selectByExample(SysAccessTokExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    SysAccessTok selectByPrimaryKey(String accessTok);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysAccessTok record, @Param("example") SysAccessTokExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysAccessTok record, @Param("example") SysAccessTokExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAccessTok record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_access_tok
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAccessTok record);
}