package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysFee;
import yxinfo.dct.service.base.dao.model.SysFeeExample;

public interface SysFeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    int countByExample(SysFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    int deleteByExample(SysFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String itemNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    int insert(SysFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    int insertSelective(SysFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    List<SysFee> selectByExample(SysFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    SysFee selectByPrimaryKey(String itemNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysFee record, @Param("example") SysFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysFee record, @Param("example") SysFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_fee
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysFee record);
}