package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysMbrInput;
import yxinfo.dct.service.base.dao.model.SysMbrInputExample;

public interface SysMbrInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    int countByExample(SysMbrInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    int deleteByExample(SysMbrInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    int insert(SysMbrInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    int insertSelective(SysMbrInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    List<SysMbrInput> selectByExample(SysMbrInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    SysMbrInput selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysMbrInput record, @Param("example") SysMbrInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysMbrInput record, @Param("example") SysMbrInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysMbrInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mbr_input
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysMbrInput record);
}