package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysMemberOrg;
import yxinfo.dct.service.base.dao.model.SysMemberOrgExample;

public interface SysMemberOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    int countByExample(SysMemberOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    int deleteByExample(SysMemberOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    int insert(SysMemberOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    int insertSelective(SysMemberOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    List<SysMemberOrg> selectByExample(SysMemberOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    SysMemberOrg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysMemberOrg record, @Param("example") SysMemberOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysMemberOrg record, @Param("example") SysMemberOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysMemberOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysMemberOrg record);
}