package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysMemberGroup;
import yxinfo.dct.service.base.dao.model.SysMemberGroupExample;

public interface SysMemberGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    int countByExample(SysMemberGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    int deleteByExample(SysMemberGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    int insert(SysMemberGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    int insertSelective(SysMemberGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    List<SysMemberGroup> selectByExample(SysMemberGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    SysMemberGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysMemberGroup record, @Param("example") SysMemberGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysMemberGroup record, @Param("example") SysMemberGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysMemberGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysMemberGroup record);
}