package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysMemberOrgRole;
import yxinfo.dct.service.base.dao.model.SysMemberOrgRoleExample;

public interface SysMemberOrgRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    int countByExample(SysMemberOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    int deleteByExample(SysMemberOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    int insert(SysMemberOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    int insertSelective(SysMemberOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    List<SysMemberOrgRole> selectByExample(SysMemberOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    SysMemberOrgRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysMemberOrgRole record, @Param("example") SysMemberOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysMemberOrgRole record, @Param("example") SysMemberOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysMemberOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member_org_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysMemberOrgRole record);
}