package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysOrgBop;
import yxinfo.dct.service.base.dao.model.SysOrgBopExample;

public interface SysOrgBopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    int countByExample(SysOrgBopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    int deleteByExample(SysOrgBopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    int insert(SysOrgBop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    int insertSelective(SysOrgBop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    List<SysOrgBop> selectByExample(SysOrgBopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    SysOrgBop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysOrgBop record, @Param("example") SysOrgBopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysOrgBop record, @Param("example") SysOrgBopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysOrgBop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_bop
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysOrgBop record);
}