package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysOrgTerminal;
import yxinfo.dct.service.base.dao.model.SysOrgTerminalExample;

public interface SysOrgTerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_terminal
     *
     * @mbggenerated
     */
    int countByExample(SysOrgTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_terminal
     *
     * @mbggenerated
     */
    int deleteByExample(SysOrgTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_terminal
     *
     * @mbggenerated
     */
    int insert(SysOrgTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_terminal
     *
     * @mbggenerated
     */
    int insertSelective(SysOrgTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_terminal
     *
     * @mbggenerated
     */
    List<SysOrgTerminal> selectByExample(SysOrgTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_terminal
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysOrgTerminal record, @Param("example") SysOrgTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_terminal
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysOrgTerminal record, @Param("example") SysOrgTerminalExample example);
}