package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysOrgFee;
import yxinfo.dct.service.base.dao.model.SysOrgFeeExample;
import yxinfo.dct.service.base.dao.model.SysOrgFeeKey;

public interface SysOrgFeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    int countByExample(SysOrgFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    int deleteByExample(SysOrgFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SysOrgFeeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    int insert(SysOrgFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    int insertSelective(SysOrgFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    List<SysOrgFee> selectByExample(SysOrgFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    SysOrgFee selectByPrimaryKey(SysOrgFeeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysOrgFee record, @Param("example") SysOrgFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysOrgFee record, @Param("example") SysOrgFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysOrgFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_fee
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysOrgFee record);
}