package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysTicket;
import yxinfo.dct.service.base.dao.model.SysTicketExample;

public interface SysTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    int countByExample(SysTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    int deleteByExample(SysTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String ticket);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    int insert(SysTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    int insertSelective(SysTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    List<SysTicket> selectByExample(SysTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    SysTicket selectByPrimaryKey(String ticket);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysTicket record, @Param("example") SysTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysTicket record, @Param("example") SysTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysTicket record);
}