package yxinfo.dct.service.base.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yxinfo.dct.service.base.dao.model.SysTag;
import yxinfo.dct.service.base.dao.model.SysTagExample;

public interface SysTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int countByExample(SysTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int deleteByExample(SysTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int insert(SysTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int insertSelective(SysTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    List<SysTag> selectByExample(SysTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    SysTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysTag record, @Param("example") SysTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysTag record, @Param("example") SysTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysTag record);
}